### PR TITLE
Fixes issue #1

### PR DESCRIPTION
**Pull request by Masqueey**
Fix to issue: https://github.com/zoli/nordtray/issues/1

*Disclaimer*: I have no experience with Go and have not tried the above code. (Sorry in advance.) 
If you explain to me how to work around the flags, hashes and checksums (or point me to a good source), I'll see if I can get it working.

### CODE REVIEW

**Comment by zoli** [comment]
For me in i3 it only shows the icon on hover it shows the title. I don't think it is needed to have any title at all (no need to toggling option for label). We can just set it to empty.

I will put some instruction on how to build this soon so  you can confirm that the problem is resolved.

**Comment by zoli** [comment]
@Masqueey You can test it with running:
```
make build
./nordtray
```

No need to the toggling part just remove `systray.SetTitle("NordTray") ` and test it if worked I will merge it.

**Comment by Masqueey** [comment]
Still missed this bit before I could generate and build:
```
go get github.com/cratonica/2goarray
```

**Comment by Masqueey** [comment]
This commit is just with the tray title removed. Compiles just fine.

**Pull request merged**
